// +build !testmock

// Code generated by mockery v2.43.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CliRuler is an autogenerated mock type for the CliRuler type
type CliRuler struct {
	mock.Mock
}

// createModel provides a mock function with given fields:
func (_m *CliRuler) createModel() {
	_m.Called()
}

// createRepository provides a mock function with given fields:
func (_m *CliRuler) createRepository() {
	_m.Called()
}

// NewCliRuler creates a new instance of CliRuler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCliRuler(t interface {
	mock.TestingT
	Cleanup(func())
}) *CliRuler {
	mock := &CliRuler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
