// +build !testmock

// Code generated by mockery v2.43.1. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/RandySteven/neo-postman/entities/models"
	mock "github.com/stretchr/testify/mock"
)

// JiraIssueRepository is an autogenerated mock type for the JiraIssueRepository type
type JiraIssueRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, id
func (_m *JiraIssueRepository) Delete(ctx context.Context, id uint64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: ctx
func (_m *JiraIssueRepository) FindAll(ctx context.Context) ([]*models.JiraIssue, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*models.JiraIssue
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*models.JiraIssue, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*models.JiraIssue); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.JiraIssue)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *JiraIssueRepository) FindByID(ctx context.Context, id uint64) (*models.JiraIssue, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.JiraIssue
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (*models.JiraIssue, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) *models.JiraIssue); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.JiraIssue)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, request
func (_m *JiraIssueRepository) Save(ctx context.Context, request *models.JiraIssue) (*models.JiraIssue, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *models.JiraIssue
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.JiraIssue) (*models.JiraIssue, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.JiraIssue) *models.JiraIssue); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.JiraIssue)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.JiraIssue) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, request
func (_m *JiraIssueRepository) Update(ctx context.Context, request *models.JiraIssue) (*models.JiraIssue, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *models.JiraIssue
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.JiraIssue) (*models.JiraIssue, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.JiraIssue) *models.JiraIssue); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.JiraIssue)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.JiraIssue) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewJiraIssueRepository creates a new instance of JiraIssueRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJiraIssueRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *JiraIssueRepository {
	mock := &JiraIssueRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
