// +build !testmock

// Code generated by mockery v2.43.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// JiraActionContract is an autogenerated mock type for the JiraActionContract type
type JiraActionContract struct {
	mock.Mock
}

// CreateJiraTicket provides a mock function with given fields:
func (_m *JiraActionContract) CreateJiraTicket() {
	_m.Called()
}

// NewJiraActionContract creates a new instance of JiraActionContract. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJiraActionContract(t interface {
	mock.TestingT
	Cleanup(func())
}) *JiraActionContract {
	mock := &JiraActionContract{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
