// +build !testmock

// Code generated by mockery v2.43.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PostgresActionContract is an autogenerated mock type for the PostgresActionContract type
type PostgresActionContract struct {
	mock.Mock
}

// NewPostgresActionContract creates a new instance of PostgresActionContract. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPostgresActionContract(t interface {
	mock.TestingT
	Cleanup(func())
}) *PostgresActionContract {
	mock := &PostgresActionContract{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
