// +build !testmock

// Code generated by mockery v2.43.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RedisActionContract is an autogenerated mock type for the RedisActionContract type
type RedisActionContract struct {
	mock.Mock
}

// ConnectToRedis provides a mock function with given fields:
func (_m *RedisActionContract) ConnectToRedis() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ConnectToRedis")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRedisActionContract creates a new instance of RedisActionContract. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRedisActionContract(t interface {
	mock.TestingT
	Cleanup(func())
}) *RedisActionContract {
	mock := &RedisActionContract{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
