// +build !testmock

// Code generated by mockery v2.43.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// String is an autogenerated mock type for the String type
type String struct {
	mock.Mock
}

// ToString provides a mock function with given fields:
func (_m *String) ToString() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ToString")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewString creates a new instance of String. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewString(t interface {
	mock.TestingT
	Cleanup(func())
}) *String {
	mock := &String{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
