// +build !testmock

// Code generated by mockery v2.43.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TestDataScheduler is an autogenerated mock type for the TestDataScheduler type
type TestDataScheduler struct {
	mock.Mock
}

// AutoDeleteUnsavedTestData provides a mock function with given fields: ctx
func (_m *TestDataScheduler) AutoDeleteUnsavedTestData(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for AutoDeleteUnsavedTestData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTestDataScheduler creates a new instance of TestDataScheduler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTestDataScheduler(t interface {
	mock.TestingT
	Cleanup(func())
}) *TestDataScheduler {
	mock := &TestDataScheduler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
