// +build !testmock

// Code generated by mockery v2.43.1. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// TestDataHandler is an autogenerated mock type for the TestDataHandler type
type TestDataHandler struct {
	mock.Mock
}

// CreateTestAPI provides a mock function with given fields: w, r
func (_m *TestDataHandler) CreateTestAPI(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetAllRecords provides a mock function with given fields: w, r
func (_m *TestDataHandler) GetAllRecords(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetDetailRecord provides a mock function with given fields: w, r
func (_m *TestDataHandler) GetDetailRecord(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// SaveRecord provides a mock function with given fields: w, r
func (_m *TestDataHandler) SaveRecord(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// UnsavedRecord provides a mock function with given fields: w, r
func (_m *TestDataHandler) UnsavedRecord(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// NewTestDataHandler creates a new instance of TestDataHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTestDataHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *TestDataHandler {
	mock := &TestDataHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
