// +build !testmock

// Code generated by mockery v2.43.1. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// TestRecordHandler is an autogenerated mock type for the TestRecordHandler type
type TestRecordHandler struct {
	mock.Mock
}

// CreateTestRecord provides a mock function with given fields: w, r
func (_m *TestRecordHandler) CreateTestRecord(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetAllTestRecords provides a mock function with given fields: w, r
func (_m *TestRecordHandler) GetAllTestRecords(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetTestRecordDetail provides a mock function with given fields: w, r
func (_m *TestRecordHandler) GetTestRecordDetail(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// NewTestRecordHandler creates a new instance of TestRecordHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTestRecordHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *TestRecordHandler {
	mock := &TestRecordHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
